### ISSUE TITLE
There is no code

### ISSUE THREAD

**Issue by RobertMcCoy** [RobertMcCoy/MelvorIdle-Leaderboards#1]
Just a gentle reminder to myself to upload the code for the repository and get it off my machine.

**Comment by jadedtdt** [comment]
Hi, fellow leaderboard developer here. I was curious if you uploaded the code for the chrome extension? If I overlooked it please provide the github link, I only really see the website and API code. Thanks!

**Comment by RobertMcCoy** [comment]
@jadedtdt Hey...sorry for like a 2 month delay in responding, I didn't see this message! If you are still looking for the extension code I can definitely provide it! I never found a good way of obscuring my Azure Function key within the Chrome extension, so I was always hesitant to put it on GitHub (I know you can probably just grab the packets going to it to find the key if you have the extension installed, but at least that's not publicly searchable).

**Comment by jadedtdt** [comment]
@RobertMcCoy No worries, we managed to make a bookmarklet in the interim but would love to upgrade it to a Chrome Extension. I work with AWS for work, so I'm curious to try Azure! Please share the code with me via email at genebbb333@aol.com

P.S. Since we're sharing... This is what me and my friends have been using the past few months. https://github.com/melvor-hiscores/melvor-hiscores.github.io/blob/master/bookmarklet.js
Definitely open to suggestions + criticism, I don't have a lot of experience w/ javascript

Thanks,
Jadedtdt
